name: NPM Publish
on:
  push:
    branches:
      - main
      - master
jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.name 'Firebolt Caster'
      - run: git config --global user.email 'nilsbaumgartner@live.de'
      - run: cp README.md ./dev/extensions/directus-extension-auto-translation/README.md
      - run: cd ./dev/extensions/directus-extension-auto-translation && npm ci
      - run: cd ./dev/extensions/directus-extension-auto-translation && npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
