name: NPM Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.name 'Firebolt Caster'
      - run: git config --global user.email 'nilsbaumgartner@live.de'
      - name: Increase Version
          working-directory: ./dev/auto-translation-hook
          run: npm version patch -m "[RELEASE] %s
      - run: git push
      - name: Upload
          working-directory: ./dev/auto-translation-hook
          run: npm version patch -m "[RELEASE] %s
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
