name: NPM Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    if: ${{ !startsWith(github.event.head_commit.message, '[RELEASE]') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: git config --global user.name 'Firebolt Caster'
      - run: git config --global user.email 'nilsbaumgartner@live.de'
      - run: cp README.md ./dev/auto-translation-hook/README.md
      - run: git add ./dev/auto-translation-hook/README.md
      - run: git commit -m "[RELEASE] Copied README.md to dev/auto-translation-hook"
      - run: cd ./dev/auto-translation-hook && npm ci
      - run: cd ./dev/auto-translation-hook && npm run release
      - run: rm -rf ./dev/auto-translation-hook/README.md
      - run: git commit -m "[RELEASE] Removed README.md from dev/auto-translation-hook"
      - run: git push
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
